global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "twiga"
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /
    follow_redirects: true
    enable_http2: true
    static_configs:
      - targets:
          - gophercon:11212
